export const ADD_ARTICLE = "ADD_ARTICLE";
export const ADD_SUGGESTIONS = "ADD_SUGGESTIONS";
export const SUGGESTION_APPROVED = "SUGGESTION_APPROVED";
export const SUGGESTION_DELETED = "SUGGESTION_DELETED";
export const OWN_SUGGESTION_APPROVED = "OWN_SUGGESTION_APPROVED";
